### ISSUE TITLE
I am unable to run the application due to the dependencies as many dependences in requirement.txt are old and distorted. 

### ISSUE THREAD

**Issue by Prathmesh-Gupta** [Pradip-p/E-Health-Care#30]

**Comment by Pradip-p** [comment]
Hello, I understand that you are facing issues running an application due to outdated and distorted dependencies in the requirements.txt file. It can be frustrating to encounter such errors while working on a project.

I suggest reaching out to the project maintainer to check if they have updated the requirements.txt file recently. You can also try searching for updated dependencies and updating the requirements.txt file yourself.

Once you have the updated requirements.txt file, you can try running the application again. Hopefully, this will resolve the issue you are facing.

Let me know if you have any further concerns.

**Comment by Prathmesh-Gupta** [comment]
Well I tried using the latest versions also but the latest version does not
support the old libraries and there are many files so its difficult to edit
them.

**Comment by Pradip-p** [comment]
Please, check requirements.txt files.
I just update recently.

**Comment by Prathmesh-Gupta** [comment]
Can run run it in by making the virtual environment in place of the docker
As i have not used docker so i am getting it some difficulties in running
the project
If docker is the only option it would be great if you can guide me to run
the project
